[package]
name = "static-server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "fs"] }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio", "server-auto"] }
http-body-util = "0.1"
bytes = "1"
